name:                kevlar
version:             0.1.0.0
github:              "wagdav/kevlar"
license:             GPL-3.0-or-later
author:              "David Wagner"
maintainer:          "wagdav@gmail.com"
copyright:           "2018 David Wagner"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/wagdav/kevlar#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- directory
- shake
- yaml

library:
  source-dirs: src

executables:
  kevlar:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kevlar

tests:
  kevlar-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kevlar
    - hspec
