---
artifacts:
- name: src
  source: .

- name: kevlar-builder
  docker_image:
    context: docker/kevlar-builder

- name: build
  script: src/ci/build.sh
  need:
    - src
    - kevlar-builder
  caches:
    - .stack
