---
artifacts:
- name: src
  source: .

- name: hello-world-builder
  docker_image:
    context: src/docker/hello-world-builder
  need:
    - src

- name: hello-world-tester
  docker_image:
    context: src/docker/hello-world-tester
  need:
    - src

- name: build
  script: src/build.sh
  need:
    - hello-world-builder
    - src

- name: env
  environment:
    HELLO: world

- name: test
  script: src/test.sh
  platform: hello-world-tester
  need:
    - src
    - build
    - hello-world-tester
    - env
